version: '3.9'

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    networks:
      - personal_finance

networks:
  personal_finance:
    driver: bridge