const FINANCE_ID_NOT_VALID_ERROR = "FINANCE_ID_NOT_VALID_ERROR";
const DESCRIPTION_FIELD_ERROR = "DESCRIPTION_FIELD_ERROR";

module.exports = {
    FINANCE_ID_NOT_VALID_ERROR,
    DESCRIPTION_FIELD_ERROR
}